### ISSUE TITLE
Tree regeneration fails on sys-kernel/genkernel-4.3.10

### ISSUE THREAD

**Issue by org-tekeli-borisp** [macaroni-os/kit-fixups#23]
Tree regeneration fails on **sys-kernel/genkernel-4.3.10** with
 **4 downloaded from                                                      
         https://deb.debian.org/debian/pool/main/d/dmraid/dmraid_1.0.0.rc16.orig
         .tar.gz does not appear to be a valid tar.bz2 archive!**
[output-2024-08-02_12_42_00_log.txt](https://github.com/user-attachments/files/16472234/output-2024-08-02_12_42_00_log.txt)

**Comment by org-tekeli-borisp** [comment]
@cuantar related to https://github.com/macaroni-os/kit-fixups/pull/13 ?

**Comment by org-tekeli-borisp** [comment]
@cuantar  Local doit doesnt work either
```
╰ $ doit
INFO     Autogen: sys-kernel/genkernel-4.3.10                                                                                                                                                                                                                                                                       
ERROR    File /home/borisp/repo_tmp/tmp/spider/CODWJ36B-3f409caaa02d702414251e0cfd508074 downloaded from https://deb.debian.org/debian/pool/main/d/dmraid/dmraid_1.0.0.rc16.orig.tar.gz does not appear to be a valid tar.bz2 archive!                                                                              
         Traceback (most recent call last):                                                                                                                                                                                                                                                                         
           File "/usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py", line 564, in lil_coroutine                                                                                                                                                                                                     
             status = await a.ensure_completed()                                                                                                                                                                                                                                                                    
           File "/usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py", line 381, in ensure_completed                                                                                                                                                                                                  
             return await self.ensure_fetched()                                                                                                                                                                                                                                                                     
           File "/usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py", line 368, in ensure_fetched                                                                                                                                                                                                    
             self.blos_object = await pkgtools.model.fastpull_session.get_file_by_url(req)                                                                                                                                                                                                                          
           File "/usr/lib/python3.9/site-packages/metatools/fastpull/core.py", line 91, in get_file_by_url                                                                                                                                                                                                          
             new_ref = await self.parent.spider.download(request,                                                                                                                                                                                                                                                   
           File "/usr/lib/python3.9/site-packages/metatools/fastpull/spider.py", line 512, in download                                                                                                                                                                                                              
             response = await download.launch()                                                                                                                                                                                                                                                                     
           File "/usr/lib/python3.9/site-packages/metatools/fastpull/spider.py", line 314, in launch                                                                                                                                                                                                                
             completion_result = await completion_fn(completion_result)                                                                                                                                                                                                                                             
           File "/usr/lib/python3.9/site-packages/metatools/fastpull/core.py", line 150, in verify_callback                                                                                                                                                                                                         
             raise FileIntegrityError(f"File {download.temp_path} downloaded from {download.request.url} does not appear to be a valid {arc_desc} archive!")                                                                                                                                                        
         metatools.fastpull.core.FileIntegrityError: File /home/borisp/repo_tmp/tmp/spider/CODWJ36B-3f409caaa02d702414251e0cfd508074 downloaded from https://deb.debian.org/debian/pool/main/d/dmraid/dmraid_1.0.0.rc16.orig.tar.gz does not appear to be a valid tar.bz2 archive!                                  
INFO     Download from https://github.com/g2p/bcache-tools/archive/399021549984ad27bf4a13ae85e458833fe003d7.tar.gz verified as valid tar.gz archive.                                                                                                                                                                
INFO     Download from https://github.com/gentoo/genkernel/tarball/d6a77d90fd511b04b12bd7ae40d710d3d144c077 verified as valid tar.gz archive.                                                                                                                                                                       
INFO     Download from https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-30.tar.xz verified as valid tar.xz archive.                                                                                                                                                                                          
INFO     Download from https://github.com/libexpat/libexpat/releases/download/R_2_5_0/expat-2.5.0.tar.xz verified as valid tar.xz archive.                                                                                                                                                                          
INFO     Download from https://github.com/open-iscsi/open-iscsi/archive/2.1.8.tar.gz verified as valid tar.gz archive.                                                                                                                                                                                              
INFO     Download from https://s3.amazonaws.com/json-c_releases/releases/json-c-0.13.1.tar.gz verified as valid tar.gz archive.                                                                                                                                                                                     
INFO     Download from https://releases.pagure.org/libaio/libaio-0.3.113.tar.gz verified as valid tar.gz archive.                                                                                                                                                                                                   
INFO     Download from https://github.com/libfuse/libfuse/releases/download/fuse-2.9.9/fuse-2.9.9.tar.gz verified as valid tar.gz archive.                                                                                                                                                                          
INFO     Download from https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.9.4.tar.bz2 verified as valid tar.bz2 archive.                                                                                                                                                                                            
INFO     Download from https://www.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v6.3.2.tar.xz verified as valid tar.xz archive.                                                                                                                                                                 
INFO     Download from https://git.kernel.org/pub/scm/linux/kernel/git/dhowells/keyutils.git/snapshot/keyutils-1.6.3.tar.gz verified as valid tar.gz archive.                                                                                                                                                       
INFO     Download from https://www.oberhumer.com/opensource/lzo/download/lzo-2.10.tar.gz verified as valid tar.gz archive.                                                                                                                                                                                          
INFO     Download from https://gnupg.org/ftp/gcrypt/gnupg/gnupg-1.4.23.tar.bz2 verified as valid tar.bz2 archive.                                                                                                                                                                                                   
INFO     Download from https://github.com/gentoo/hwids/archive/hwids-20210613.tar.gz verified as valid tar.gz archive.                                                                                                                                                                                              
INFO     Download from https://gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.43.tar.bz2 verified as valid tar.bz2 archive.                                                                                                                                                                                       
INFO     Download from https://www.kernel.org/pub/linux/utils/raid/mdadm/mdadm-4.1.tar.xz verified as valid tar.xz archive.                                                                                                                                                                                         
INFO     Download from https://github.com/besser82/libxcrypt/releases/download/v4.4.36/libxcrypt-4.4.36.tar.xz verified as valid tar.xz archive.                                                                                                                                                                    
INFO     Download from https://github.com/facebook/zstd/archive/v1.5.5.tar.gz verified as valid tar.gz archive.                                                                                                                                                                                                     
INFO     Download from https://www.kernel.org/pub/linux/kernel/people/tytso/e2fsprogs/v1.46.4/e2fsprogs-1.46.4.tar.xz verified as valid tar.xz archive.                                                                                                                                                             
INFO     Download from https://github.com/rpodgorny/unionfs-fuse/archive/v2.0.tar.gz verified as valid tar.gz archive.                                                                                                                                                                                              
INFO     Download from https://matt.ucc.asn.au/dropbear/releases/dropbear-2022.83.tar.bz2 verified as valid tar.bz2 archive.                                                                                                                                                                                        
INFO     Download from https://dev.gentoo.org/~blueness/eudev/eudev-3.2.10.tar.gz verified as valid tar.gz archive.                                                                                                                                                                                                 
INFO     Download from https://github.com/jthornber/thin-provisioning-tools/archive/v0.9.0.tar.gz verified as valid tar.gz archive.                                                                                                                                                                                 
INFO     Download from https://zlib.net/zlib-1.3.1.tar.gz verified as valid tar.gz archive.                                                                                                                                                                                                                         
INFO     Download from https://www.kernel.org/pub/linux/utils/fs/xfs/xfsprogs/xfsprogs-6.3.0.tar.xz verified as valid tar.xz archive.                                                                                                                                                                               
INFO     Download from https://tukaani.org/xz/xz-5.4.3.tar.gz verified as valid tar.gz archive.                                                                                                                                                                                                                     
INFO     Download from https://lttng.org/files/urcu/userspace-rcu-0.14.0.tar.bz2 verified as valid tar.bz2 archive.                                                                                                                                                                                                 
INFO     Download from https://github.com/strace/strace/releases/download/v6.4/strace-6.4.tar.xz verified as valid tar.xz archive.                                                                                                                                                                                  
INFO     Download from https://www.kernel.org/pub/linux/utils/cryptsetup/v2.6/cryptsetup-2.6.1.tar.xz verified as valid tar.xz archive.                                                                                                                                                                             
INFO     Download from https://www.kernel.org/pub/linux/utils/util-linux/v2.38/util-linux-2.38.1.tar.xz verified as valid tar.xz archive.                                                                                                                                                                           
INFO     Download from https://ftpmirror.gnu.org/coreutils/coreutils-9.3.tar.xz verified as valid tar.xz archive.                                                                                                                                                                                                   
INFO     Download from https://ftp.osuosl.org/pub/rpm/popt/releases/popt-1.x/popt-1.19.tar.gz verified as valid tar.gz archive.                                                                                                                                                                                     
INFO     Download from https://www.busybox.net/downloads/busybox-1.36.1.tar.bz2 verified as valid tar.bz2 archive.                                                                                                                                                                                                  
INFO     Download from https://boostorg.jfrog.io/artifactory/main/release/1.79.0/source/boost_1_79_0.tar.bz2 verified as valid tar.bz2 archive.                                                                                                                                                                     
INFO     Created: genkernel-4.3.10.ebuild                                                                                                                                                                                                                                                                           
ERROR    File /home/borisp/repo_tmp/tmp/spider/F2I37Q26-3f409caaa02d702414251e0cfd508074 downloaded from https://deb.debian.org/debian/pool/main/d/dmraid/dmraid_1.0.0.rc16.orig.tar.gz does not appear to be a valid tar.bz2 archive!                                                                              
         Traceback (most recent call last):                                                                                                                                                                                                                                                                         
           File "/usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py", line 601, in wrapper                                                                                                                                                                                                           
             await self.generate()                                                                                                                                                                                                                                                                                  
           File "/usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py", line 730, in generate                                                                                                                                                                                                          
             await self.record_manifest_lines()                                                                                                                                                                                                                                                                     
           File "/usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py", line 679, in record_manifest_lines                                                                                                                                                                                             
             success = await artifact.ensure_completed()                                                                                                                                                                                                                                                            
           File "/usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py", line 381, in ensure_completed                                                                                                                                                                                                  
             return await self.ensure_fetched()                                                                                                                                                                                                                                                                     
           File "/usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py", line 368, in ensure_fetched                                                                                                                                                                                                    
             self.blos_object = await pkgtools.model.fastpull_session.get_file_by_url(req)                                                                                                                                                                                                                          
           File "/usr/lib/python3.9/site-packages/metatools/fastpull/core.py", line 91, in get_file_by_url                                                                                                                                                                                                          
             new_ref = await self.parent.spider.download(request,                                                                                                                                                                                                                                                   
           File "/usr/lib/python3.9/site-packages/metatools/fastpull/spider.py", line 512, in download                                                                                                                                                                                                              
             response = await download.launch()                                                                                                                                                                                                                                                                     
           File "/usr/lib/python3.9/site-packages/metatools/fastpull/spider.py", line 314, in launch                                                                                                                                                                                                                
             completion_result = await completion_fn(completion_result)                                                                                                                                                                                                                                             
           File "/usr/lib/python3.9/site-packages/metatools/fastpull/core.py", line 150, in verify_callback                                                                                                                                                                                                         
             raise FileIntegrityError(f"File {download.temp_path} downloaded from {download.request.url} does not appear to be a valid {arc_desc} archive!")                                                                                                                                                        
         metatools.fastpull.core.FileIntegrityError: File /home/borisp/repo_tmp/tmp/spider/F2I37Q26-3f409caaa02d702414251e0cfd508074 downloaded from https://deb.debian.org/debian/pool/main/d/dmraid/dmraid_1.0.0.rc16.orig.tar.gz does not appear to be a valid tar.bz2 archive!                                  
ERROR    Autogen failed (count: 1). [<Task finished name='Task-9' coro=<BreezyBuild.push.<locals>.wrapper() done, defined at /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:599> exception=FileIntegrityError('File /home/borisp/repo_tmp/tmp/spider/F2I37Q26-3f409caaa02d702414251e0cfd508074   
         downloaded from https://deb.debian.org/debian/pool/main/d/dmraid/dmraid_1.0.0.rc16.orig.tar.gz does not appear to be a valid tar.bz2 archive!')>]                                                                                                                                                          
ERROR    Errors were encountered when processing the following autogens:                                                                                                                                                                                                                                            
ERROR     * sys-kernel/genkernel-4.3.10                                                                                                                                                                                                                                                                             
ERROR    End of report.                 
```

**Comment by org-tekeli-borisp** [comment]
@cuantar if I change .bz2 to .gz again  
![image](https://github.com/user-attachments/assets/a86c36f7-d525-4153-bf85-ba39359adef5)
doit successes
```
 ╰ $ doit
INFO     Autogen: sys-kernel/genkernel-4.3.10                                                                                                                                                                                                                                                                       
INFO     Download from https://deb.debian.org/debian/pool/main/d/dmraid/dmraid_1.0.0.rc16.orig.tar.gz verified as valid tar.gz archive.                                                                                                                                                                             
INFO     Created: genkernel-4.3.10.ebuild         
```
